export interface ToolCategory {
  name: string;
  slug: string;
  icon: string;
}

export interface ToolConfig {
  slug: string;
  name: string;
  description: string;
  icon: string;
  category: string;
  metaTitle: string;
  metaDescription: string;
  keywords: string[];
}

export const categories: ToolCategory[] = [
  { name: "Text & Dev Tools", slug: "text-dev", icon: "🛠️" },
  { name: "Generators & Security", slug: "generators-security", icon: "🔐" },
  { name: "Image Tools", slug: "image", icon: "🖼️" },
  { name: "Document Tools", slug: "document", icon: "📄" },
  { name: "Daily Use Tools", slug: "daily-use", icon: "🧮" },
  { name: "SEO & Content Tools", slug: "seo-content", icon: "📊" },
  { name: "Text Processing", slug: "text-processing", icon: "📝" },
  { name: "Business & Finance", slug: "business-finance", icon: "💼" },
  { name: "Productivity", slug: "productivity", icon: "⏱️" },
  { name: "Dev Helpers", slug: "dev-helpers", icon: "⚙️" },
  { name: "CSS & Design", slug: "css-design", icon: "🎨" },
  { name: "Fun & Social", slug: "fun-social", icon: "🎮" },
];

export const tools: ToolConfig[] = [
  // TEXT & DEV TOOLS
  {
    slug: "json-formatter",
    icon: "📐",
    name: "JSON Formatter",
    description: "Format and beautify JSON data with proper indentation",
    category: "text-dev",
    metaTitle: "JSON Formatter & Beautifier Online - Free Tool | iamnoobs",
    metaDescription: "Format, beautify, and validate your JSON data instantly. Free online JSON formatter with syntax highlighting, copy, and download options.",
    keywords: ["json formatter", "json beautifier", "format json", "json pretty print"],
  },
  {
    slug: "json-validator",
    icon: "✅",
    name: "JSON Validator",
    description: "Validate JSON data and find syntax errors instantly",
    category: "text-dev",
    metaTitle: "JSON Validator Online - Check JSON Syntax Free | iamnoobs",
    metaDescription: "Validate your JSON data and find syntax errors instantly. Free online JSON validator with detailed error messages.",
    keywords: ["json validator", "validate json", "json syntax checker", "json lint"],
  },
  {
    slug: "json-to-xml",
    icon: "🔄",
    name: "JSON to XML Converter",
    description: "Convert JSON data to XML format quickly",
    category: "text-dev",
    metaTitle: "JSON to XML Converter Online - Free Tool | iamnoobs",
    metaDescription: "Convert JSON data to well-formatted XML instantly. Free online converter with copy and download options.",
    keywords: ["json to xml", "convert json to xml", "json xml converter"],
  },
  {
    slug: "xml-to-json",
    icon: "🔄",
    name: "XML to JSON Converter",
    description: "Convert XML data to JSON format easily",
    category: "text-dev",
    metaTitle: "XML to JSON Converter Online - Free Tool | iamnoobs",
    metaDescription: "Convert XML data to clean JSON format instantly. Free online converter with validation and download options.",
    keywords: ["xml to json", "convert xml to json", "xml json converter"],
  },
  {
    slug: "html-formatter",
    icon: "🌐",
    name: "HTML Formatter",
    description: "Format and beautify HTML code with proper indentation",
    category: "text-dev",
    metaTitle: "HTML Formatter & Beautifier Online - Free Tool | iamnoobs",
    metaDescription: "Format and beautify your HTML code with proper indentation. Free online HTML formatter and prettifier.",
    keywords: ["html formatter", "html beautifier", "format html", "html pretty print"],
  },
  {
    slug: "html-minifier",
    icon: "🗜️",
    name: "HTML Minifier",
    description: "Minify HTML code by removing whitespace and comments",
    category: "text-dev",
    metaTitle: "HTML Minifier Online - Compress HTML Free | iamnoobs",
    metaDescription: "Minify and compress your HTML code by removing unnecessary whitespace and comments. Free online HTML minifier.",
    keywords: ["html minifier", "minify html", "compress html", "html compressor"],
  },
  {
    slug: "css-minifier",
    icon: "🎨",
    name: "CSS Minifier",
    description: "Minify CSS code to reduce file size",
    category: "text-dev",
    metaTitle: "CSS Minifier Online - Compress CSS Free | iamnoobs",
    metaDescription: "Minify and compress your CSS code to reduce file size. Free online CSS minifier with instant results.",
    keywords: ["css minifier", "minify css", "compress css", "css compressor"],
  },
  {
    slug: "javascript-minifier",
    icon: "⚡",
    name: "JavaScript Minifier",
    description: "Minify JavaScript code to reduce file size",
    category: "text-dev",
    metaTitle: "JavaScript Minifier Online - Compress JS Free | iamnoobs",
    metaDescription: "Minify and compress your JavaScript code. Free online JS minifier to reduce bundle size.",
    keywords: ["javascript minifier", "js minifier", "minify javascript", "compress js"],
  },
  {
    slug: "sql-formatter",
    icon: "🗃️",
    name: "SQL Formatter",
    description: "Format and beautify SQL queries with proper indentation",
    category: "text-dev",
    metaTitle: "SQL Formatter & Beautifier Online - Free Tool | iamnoobs",
    metaDescription: "Format and beautify your SQL queries with proper indentation. Free online SQL formatter.",
    keywords: ["sql formatter", "sql beautifier", "format sql", "sql pretty print"],
  },
  {
    slug: "base64-encoder",
    icon: "🔐",
    name: "Base64 Encoder",
    description: "Encode text to Base64 format instantly",
    category: "text-dev",
    metaTitle: "Base64 Encoder Online - Encode Text Free | iamnoobs",
    metaDescription: "Encode any text or string to Base64 format instantly. Free online Base64 encoder tool.",
    keywords: ["base64 encoder", "encode base64", "text to base64", "base64 encoding"],
  },
  {
    slug: "base64-decoder",
    icon: "🔓",
    name: "Base64 Decoder",
    description: "Decode Base64 encoded strings back to text",
    category: "text-dev",
    metaTitle: "Base64 Decoder Online - Decode Base64 Free | iamnoobs",
    metaDescription: "Decode Base64 encoded strings back to readable text. Free online Base64 decoder tool.",
    keywords: ["base64 decoder", "decode base64", "base64 to text", "base64 decoding"],
  },
  {
    slug: "url-encoder",
    icon: "🔗",
    name: "URL Encoder",
    description: "Encode text for safe use in URLs",
    category: "text-dev",
    metaTitle: "URL Encoder Online - Encode URL Components Free | iamnoobs",
    metaDescription: "Encode text for safe use in URLs. Free online URL encoder for special characters and query parameters.",
    keywords: ["url encoder", "encode url", "url encoding", "percent encoding"],
  },
  {
    slug: "url-decoder",
    icon: "🔗",
    name: "URL Decoder",
    description: "Decode URL-encoded strings back to readable text",
    category: "text-dev",
    metaTitle: "URL Decoder Online - Decode URL Free | iamnoobs",
    metaDescription: "Decode URL-encoded strings back to human-readable text. Free online URL decoder tool.",
    keywords: ["url decoder", "decode url", "url decoding", "percent decoding"],
  },
  {
    slug: "text-case-converter",
    icon: "🔠",
    name: "Text Case Converter",
    description: "Convert text between uppercase, lowercase, title case and more",
    category: "text-dev",
    metaTitle: "Text Case Converter Online - Change Text Case Free | iamnoobs",
    metaDescription: "Convert text between uppercase, lowercase, title case, camelCase, and more. Free online text case converter.",
    keywords: ["text case converter", "change case", "uppercase converter", "lowercase converter"],
  },
  {
    slug: "text-diff-checker",
    icon: "📊",
    name: "Text Diff Checker",
    description: "Compare two texts and find the differences",
    category: "text-dev",
    metaTitle: "Text Diff Checker Online - Compare Text Free | iamnoobs",
    metaDescription: "Compare two texts side by side and find exact differences. Free online diff checker and text comparison tool.",
    keywords: ["text diff", "diff checker", "compare text", "text comparison"],
  },

  // GENERATORS & SECURITY
  {
    slug: "uuid-generator",
    icon: "🆔",
    name: "UUID Generator",
    description: "Generate random UUIDs (v4) instantly",
    category: "generators-security",
    metaTitle: "UUID Generator Online - Generate UUID v4 Free | iamnoobs",
    metaDescription: "Generate random UUID v4 identifiers instantly. Free online UUID generator with bulk generation and copy options.",
    keywords: ["uuid generator", "generate uuid", "uuid v4", "random uuid"],
  },
  {
    slug: "password-generator",
    icon: "🔑",
    name: "Password Generator",
    description: "Generate strong, secure passwords with custom options",
    category: "generators-security",
    metaTitle: "Password Generator Online - Strong Passwords Free | iamnoobs",
    metaDescription: "Generate strong, secure passwords with custom length, symbols, numbers, and more. Free online password generator.",
    keywords: ["password generator", "strong password", "random password", "secure password generator"],
  },
  {
    slug: "lorem-ipsum-generator",
    icon: "📜",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder text for your designs",
    category: "generators-security",
    metaTitle: "Lorem Ipsum Generator Online - Placeholder Text Free | iamnoobs",
    metaDescription: "Generate lorem ipsum placeholder text for your designs and mockups. Free online lorem ipsum generator.",
    keywords: ["lorem ipsum generator", "placeholder text", "dummy text", "lorem ipsum"],
  },
  {
    slug: "slug-generator",
    icon: "🏷️",
    name: "Slug Generator",
    description: "Convert text to URL-friendly slugs",
    category: "generators-security",
    metaTitle: "Slug Generator Online - URL Slug Creator Free | iamnoobs",
    metaDescription: "Convert any text to SEO-friendly URL slugs instantly. Free online slug generator for websites and blogs.",
    keywords: ["slug generator", "url slug", "slug creator", "url-friendly text"],
  },
  {
    slug: "hash-generator",
    icon: "🧬",
    name: "Hash Generator",
    description: "Generate MD5, SHA-1, and SHA-256 hashes",
    category: "generators-security",
    metaTitle: "Hash Generator Online - MD5, SHA-1, SHA-256 Free | iamnoobs",
    metaDescription: "Generate MD5, SHA-1, and SHA-256 hashes from any text. Free online hash generator tool.",
    keywords: ["hash generator", "md5 hash", "sha256 hash", "sha1 hash"],
  },
  {
    slug: "hmac-generator",
    icon: "🛡️",
    name: "HMAC Generator",
    description: "Generate HMAC authentication codes",
    category: "generators-security",
    metaTitle: "HMAC Generator Online - Create HMAC Free | iamnoobs",
    metaDescription: "Generate HMAC authentication codes with various hash algorithms. Free online HMAC generator tool.",
    keywords: ["hmac generator", "hmac sha256", "hmac calculator", "hmac authentication"],
  },
  {
    slug: "jwt-decoder",
    icon: "🎟️",
    name: "JWT Decoder",
    description: "Decode and inspect JSON Web Tokens",
    category: "generators-security",
    metaTitle: "JWT Decoder Online - Decode JWT Free | iamnoobs",
    metaDescription: "Decode and inspect JSON Web Tokens (JWT) instantly. View header, payload, and signature. Free online JWT decoder.",
    keywords: ["jwt decoder", "decode jwt", "jwt inspector", "json web token decoder"],
  },
  {
    slug: "jwt-encoder",
    icon: "🎫",
    name: "JWT Encoder",
    description: "Create and encode JSON Web Tokens",
    category: "generators-security",
    metaTitle: "JWT Encoder Online - Create JWT Free | iamnoobs",
    metaDescription: "Create and encode JSON Web Tokens with custom headers and payloads. Free online JWT encoder tool.",
    keywords: ["jwt encoder", "create jwt", "jwt creator", "json web token encoder"],
  },
  {
    slug: "regex-tester",
    icon: "🧪",
    name: "Regex Tester",
    description: "Test regular expressions against sample text",
    category: "generators-security",
    metaTitle: "Regex Tester Online - Test Regular Expressions Free | iamnoobs",
    metaDescription: "Test your regular expressions against sample text with real-time matching. Free online regex tester tool.",
    keywords: ["regex tester", "regular expression tester", "test regex", "regex matcher"],
  },
  {
    slug: "regex-generator",
    icon: "🧩",
    name: "Regex Generator",
    description: "Generate common regex patterns from descriptions",
    category: "generators-security",
    metaTitle: "Regex Generator Online - Generate Regex Patterns Free | iamnoobs",
    metaDescription: "Generate common regular expression patterns easily. Free online regex generator for emails, URLs, and more.",
    keywords: ["regex generator", "regex creator", "generate regex", "regex patterns"],
  },

  // IMAGE TOOLS
  {
    slug: "image-compressor",
    icon: "📦",
    name: "Image Compressor",
    description: "Compress images in your browser without uploading",
    category: "image",
    metaTitle: "Image Compressor Online - Compress Images Free | iamnoobs",
    metaDescription: "Compress images directly in your browser without uploading to any server. Free, private, and fast image compression.",
    keywords: ["image compressor", "compress image", "reduce image size", "image optimization"],
  },
  {
    slug: "jpg-to-png",
    icon: "🖼️",
    name: "JPG to PNG Converter",
    description: "Convert JPG images to PNG format in your browser",
    category: "image",
    metaTitle: "JPG to PNG Converter Online - Free Tool | iamnoobs",
    metaDescription: "Convert JPG images to PNG format directly in your browser. Free, private, and instant conversion.",
    keywords: ["jpg to png", "convert jpg to png", "jpeg to png", "image converter"],
  },
  {
    slug: "png-to-jpg",
    icon: "🖼️",
    name: "PNG to JPG Converter",
    description: "Convert PNG images to JPG format in your browser",
    category: "image",
    metaTitle: "PNG to JPG Converter Online - Free Tool | iamnoobs",
    metaDescription: "Convert PNG images to JPG format directly in your browser. Free, private, and instant conversion.",
    keywords: ["png to jpg", "convert png to jpg", "png to jpeg", "image converter"],
  },
  {
    slug: "webp-converter",
    icon: "🔃",
    name: "WebP Converter",
    description: "Convert images to WebP format for better web performance",
    category: "image",
    metaTitle: "WebP Converter Online - Convert to WebP Free | iamnoobs",
    metaDescription: "Convert images to WebP format for faster loading. Free online WebP converter with quality controls.",
    keywords: ["webp converter", "convert to webp", "image to webp", "webp format"],
  },
  {
    slug: "image-resizer",
    icon: "📐",
    name: "Image Resizer",
    description: "Resize images to custom dimensions in your browser",
    category: "image",
    metaTitle: "Image Resizer Online - Resize Images Free | iamnoobs",
    metaDescription: "Resize images to custom dimensions directly in your browser. Free online image resizer with aspect ratio lock.",
    keywords: ["image resizer", "resize image", "change image size", "image dimensions"],
  },
  {
    slug: "image-to-base64",
    icon: "🖼️",
    name: "Image to Base64",
    description: "Convert images to Base64 encoded strings",
    category: "image",
    metaTitle: "Image to Base64 Converter Online - Free Tool | iamnoobs",
    metaDescription: "Convert any image to Base64 encoded data URI. Free online image to Base64 converter for CSS and HTML.",
    keywords: ["image to base64", "base64 image", "image encoder", "data uri"],
  },
  {
    slug: "base64-to-image",
    icon: "🖼️",
    name: "Base64 to Image",
    description: "Convert Base64 strings back to downloadable images",
    category: "image",
    metaTitle: "Base64 to Image Converter Online - Free Tool | iamnoobs",
    metaDescription: "Convert Base64 encoded strings back to downloadable images. Free online Base64 to image converter.",
    keywords: ["base64 to image", "decode base64 image", "base64 image decoder"],
  },

  // DOCUMENT TOOLS
  {
    slug: "pdf-to-word",
    icon: "📄",
    name: "PDF to Word",
    description: "Convert PDF documents to editable Word format (basic support)",
    category: "document",
    metaTitle: "PDF to Word Converter Online - Free Tool | iamnoobs",
    metaDescription: "Convert PDF documents to Word format. Basic client-side PDF text extraction and conversion.",
    keywords: ["pdf to word", "pdf to docx", "convert pdf to word", "pdf converter"],
  },
  {
    slug: "word-to-pdf",
    icon: "📝",
    name: "Word to PDF",
    description: "Convert text documents to PDF format in your browser",
    category: "document",
    metaTitle: "Word to PDF Converter Online - Free Tool | iamnoobs",
    metaDescription: "Convert text documents to PDF format directly in your browser. Free and private document conversion.",
    keywords: ["word to pdf", "docx to pdf", "convert word to pdf", "document to pdf"],
  },
  {
    slug: "pdf-compressor",
    icon: "📦",
    name: "PDF Compressor",
    description: "Reduce PDF file size in your browser",
    category: "document",
    metaTitle: "PDF Compressor Online - Reduce PDF Size Free | iamnoobs",
    metaDescription: "Compress and reduce PDF file size in your browser. Free online PDF compression tool.",
    keywords: ["pdf compressor", "compress pdf", "reduce pdf size", "pdf optimization"],
  },
  {
    slug: "pdf-merger",
    icon: "📎",
    name: "PDF Merger",
    description: "Merge multiple PDF files into one document",
    category: "document",
    metaTitle: "PDF Merger Online - Merge PDFs Free | iamnoobs",
    metaDescription: "Merge multiple PDF files into one document in your browser. Free, private PDF merger tool.",
    keywords: ["pdf merger", "merge pdf", "combine pdf", "join pdf files"],
  },
  {
    slug: "pdf-splitter",
    icon: "✂️",
    name: "PDF Splitter",
    description: "Split PDF files into individual pages",
    category: "document",
    metaTitle: "PDF Splitter Online - Split PDF Pages Free | iamnoobs",
    metaDescription: "Split PDF files into individual pages in your browser. Free, private PDF splitter tool.",
    keywords: ["pdf splitter", "split pdf", "extract pdf pages", "pdf page extractor"],
  },

  // DAILY USE TOOLS
  {
    slug: "unit-converter",
    icon: "📏",
    name: "Unit Converter",
    description: "Convert between units of length, weight, and temperature",
    category: "daily-use",
    metaTitle: "Unit Converter Online - Length, Weight, Temperature | iamnoobs",
    metaDescription: "Convert between units of length, weight, and temperature instantly. Free online unit conversion tool.",
    keywords: ["unit converter", "length converter", "weight converter", "temperature converter"],
  },
  {
    slug: "currency-converter",
    icon: "💱",
    name: "Currency Converter",
    description: "Convert between world currencies with live rates",
    category: "daily-use",
    metaTitle: "Currency Converter Online - Live Exchange Rates | iamnoobs",
    metaDescription: "Convert between world currencies with live exchange rates. Free online currency converter tool.",
    keywords: ["currency converter", "exchange rate", "currency exchange", "money converter"],
  },
  {
    slug: "timezone-converter",
    icon: "🌍",
    name: "Time Zone Converter",
    description: "Convert time between different time zones",
    category: "daily-use",
    metaTitle: "Time Zone Converter Online - Convert Time Free | iamnoobs",
    metaDescription: "Convert time between different time zones instantly. Free online timezone conversion tool.",
    keywords: ["timezone converter", "time zone converter", "convert time", "world clock"],
  },
  {
    slug: "age-calculator",
    icon: "🎂",
    name: "Age Calculator",
    description: "Calculate exact age from date of birth",
    category: "daily-use",
    metaTitle: "Age Calculator Online - Calculate Your Age Free | iamnoobs",
    metaDescription: "Calculate your exact age in years, months, and days from your date of birth. Free online age calculator.",
    keywords: ["age calculator", "calculate age", "birthday calculator", "age from dob"],
  },
  {
    slug: "percentage-calculator",
    icon: "💯",
    name: "Percentage Calculator",
    description: "Calculate percentages, increases, and decreases",
    category: "daily-use",
    metaTitle: "Percentage Calculator Online - Free Tool | iamnoobs",
    metaDescription: "Calculate percentages, percentage increase/decrease, and more. Free online percentage calculator.",
    keywords: ["percentage calculator", "percent calculator", "calculate percentage"],
  },
  {
    slug: "emi-calculator",
    icon: "🏦",
    name: "EMI Calculator",
    description: "Calculate monthly EMI for loans",
    category: "daily-use",
    metaTitle: "EMI Calculator Online - Calculate Loan EMI Free | iamnoobs",
    metaDescription: "Calculate monthly EMI for home loans, car loans, and personal loans. Free online EMI calculator.",
    keywords: ["emi calculator", "loan emi", "monthly installment", "loan calculator"],
  },
  {
    slug: "discount-calculator",
    icon: "🏷️",
    name: "Discount Calculator",
    description: "Calculate discount amounts and final prices",
    category: "daily-use",
    metaTitle: "Discount Calculator Online - Calculate Savings Free | iamnoobs",
    metaDescription: "Calculate discount amounts, savings, and final prices. Free online discount and sale price calculator.",
    keywords: ["discount calculator", "calculate discount", "sale price calculator", "savings calculator"],
  },

  // SEO & CONTENT TOOLS
  {
    slug: "meta-tag-generator",
    icon: "🏗️",
    name: "Meta Tag Generator",
    description: "Generate HTML meta tags for better SEO",
    category: "seo-content",
    metaTitle: "Meta Tag Generator Online - SEO Meta Tags Free | iamnoobs",
    metaDescription: "Generate HTML meta tags for better SEO and social sharing. Free online meta tag generator with preview.",
    keywords: ["meta tag generator", "seo meta tags", "html meta tags", "meta description generator"],
  },
  {
    slug: "open-graph-generator",
    icon: "📣",
    name: "Open Graph Generator",
    description: "Generate Open Graph meta tags for social sharing",
    category: "seo-content",
    metaTitle: "Open Graph Generator Online - OG Tags Free | iamnoobs",
    metaDescription: "Generate Open Graph meta tags for better social media sharing. Free online OG tag generator.",
    keywords: ["open graph generator", "og tags", "social media tags", "facebook meta tags"],
  },
  {
    slug: "keyword-density-checker",
    icon: "🔍",
    name: "Keyword Density Checker",
    description: "Analyze keyword frequency and density in your text",
    category: "seo-content",
    metaTitle: "Keyword Density Checker Online - Free SEO Tool | iamnoobs",
    metaDescription: "Analyze keyword frequency and density in your content for better SEO. Free online keyword density checker.",
    keywords: ["keyword density", "keyword checker", "seo keyword analysis", "keyword frequency"],
  },
  {
    slug: "word-counter",
    icon: "📊",
    name: "Word Counter",
    description: "Count words, characters, sentences, and paragraphs",
    category: "seo-content",
    metaTitle: "Word Counter Online - Count Words Free | iamnoobs",
    metaDescription: "Count words, characters, sentences, and paragraphs in your text. Free online word counter with reading time estimate.",
    keywords: ["word counter", "character counter", "word count", "text statistics"],
  },
  {
    slug: "html-to-text",
    icon: "📝",
    name: "HTML to Text Converter",
    description: "Strip HTML tags and extract plain text",
    category: "seo-content",
    metaTitle: "HTML to Text Converter Online - Free Tool | iamnoobs",
    metaDescription: "Strip HTML tags and convert HTML to clean plain text. Free online HTML to text converter.",
    keywords: ["html to text", "strip html tags", "html stripper", "html to plain text"],
  },
  {
    slug: "text-to-html",
    icon: "🌐",
    name: "Text to HTML Converter",
    description: "Convert plain text to HTML with proper formatting",
    category: "seo-content",
    metaTitle: "Text to HTML Converter Online - Free Tool | iamnoobs",
    metaDescription: "Convert plain text to properly formatted HTML. Free online text to HTML converter.",
    keywords: ["text to html", "plain text to html", "convert text to html", "text html converter"],
  },

  // ADVANCED DEV & ENCODING (added to text-dev)
  {
    slug: "json-to-csv-converter",
    icon: "📊",
    name: "JSON to CSV Converter",
    description: "Convert JSON arrays to CSV format instantly",
    category: "text-dev",
    metaTitle: "JSON to CSV Converter Online - Free Tool | iamnoobs",
    metaDescription: "Convert JSON arrays to downloadable CSV files instantly. Free online JSON to CSV converter.",
    keywords: ["json to csv", "convert json to csv", "json csv converter", "json export csv"],
  },
  {
    slug: "csv-to-json-converter",
    icon: "📋",
    name: "CSV to JSON Converter",
    description: "Convert CSV data to JSON format instantly",
    category: "text-dev",
    metaTitle: "CSV to JSON Converter Online - Free Tool | iamnoobs",
    metaDescription: "Convert CSV data to structured JSON instantly. Free online CSV to JSON converter.",
    keywords: ["csv to json", "convert csv to json", "csv json converter", "csv parser"],
  },
  {
    slug: "yaml-to-json",
    icon: "📄",
    name: "YAML to JSON Converter",
    description: "Convert YAML to JSON format quickly",
    category: "text-dev",
    metaTitle: "YAML to JSON Converter Online - Free Tool | iamnoobs",
    metaDescription: "Convert YAML data to JSON format instantly. Free online YAML to JSON converter.",
    keywords: ["yaml to json", "convert yaml to json", "yaml json converter", "yaml parser"],
  },
  {
    slug: "json-to-yaml",
    icon: "📄",
    name: "JSON to YAML Converter",
    description: "Convert JSON to YAML format quickly",
    category: "text-dev",
    metaTitle: "JSON to YAML Converter Online - Free Tool | iamnoobs",
    metaDescription: "Convert JSON data to YAML format instantly. Free online JSON to YAML converter.",
    keywords: ["json to yaml", "convert json to yaml", "json yaml converter"],
  },
  {
    slug: "url-parser",
    icon: "🔎",
    name: "URL Parser",
    description: "Parse and analyze URL components",
    category: "text-dev",
    metaTitle: "URL Parser Online - Analyze URL Components Free | iamnoobs",
    metaDescription: "Parse and analyze URL components including protocol, host, path, query params, and hash. Free online URL parser.",
    keywords: ["url parser", "parse url", "url analyzer", "url components"],
  },
  {
    slug: "user-agent-parser",
    icon: "🕵️",
    name: "User Agent Parser",
    description: "Parse and decode user agent strings",
    category: "text-dev",
    metaTitle: "User Agent Parser Online - Decode UA Strings Free | iamnoobs",
    metaDescription: "Parse and decode user agent strings to identify browser, OS, and device. Free online user agent parser.",
    keywords: ["user agent parser", "parse user agent", "ua string", "browser detection"],
  },
  {
    slug: "http-header-viewer",
    icon: "📡",
    name: "HTTP Header Viewer",
    description: "View and analyze HTTP headers for any URL",
    category: "text-dev",
    metaTitle: "HTTP Header Viewer Online - Check Headers Free | iamnoobs",
    metaDescription: "Generate and analyze common HTTP request and response headers. Free online HTTP header viewer.",
    keywords: ["http header viewer", "http headers", "response headers", "request headers"],
  },
  {
    slug: "ip-lookup",
    icon: "🌐",
    name: "IP Lookup",
    description: "Look up your public IP address and details",
    category: "text-dev",
    metaTitle: "IP Lookup Online - Find Your IP Address Free | iamnoobs",
    metaDescription: "Find your public IP address and geolocation details. Free online IP lookup tool.",
    keywords: ["ip lookup", "my ip address", "ip finder", "ip geolocation"],
  },
  {
    slug: "curl-to-code",
    icon: "💻",
    name: "cURL to Code",
    description: "Convert cURL commands to code in various languages",
    category: "text-dev",
    metaTitle: "cURL to Code Converter Online - Free Tool | iamnoobs",
    metaDescription: "Convert cURL commands to JavaScript, Python, PHP, and more. Free online cURL to code converter.",
    keywords: ["curl to code", "curl converter", "curl to javascript", "curl to python"],
  },

  // TEXT PROCESSING
  {
    slug: "remove-duplicate-lines",
    icon: "🧹",
    name: "Remove Duplicate Lines",
    description: "Remove duplicate lines from text instantly",
    category: "text-processing",
    metaTitle: "Remove Duplicate Lines Online - Free Tool | iamnoobs",
    metaDescription: "Remove duplicate lines from your text instantly. Free online duplicate line remover.",
    keywords: ["remove duplicate lines", "deduplicate text", "unique lines", "remove duplicates"],
  },
  {
    slug: "sort-text-lines",
    icon: "↕️",
    name: "Sort Text Lines",
    description: "Sort lines of text alphabetically or numerically",
    category: "text-processing",
    metaTitle: "Sort Text Lines Online - Free Tool | iamnoobs",
    metaDescription: "Sort lines of text alphabetically, numerically, or in reverse. Free online text sorter.",
    keywords: ["sort text lines", "sort lines", "alphabetical sort", "text sorter"],
  },
  {
    slug: "reverse-text",
    icon: "🔁",
    name: "Reverse Text",
    description: "Reverse text, words, or lines instantly",
    category: "text-processing",
    metaTitle: "Reverse Text Online - Free Tool | iamnoobs",
    metaDescription: "Reverse text characters, words, or lines instantly. Free online text reverser.",
    keywords: ["reverse text", "text reverser", "backwards text", "mirror text"],
  },
  {
    slug: "random-string-generator",
    icon: "🎲",
    name: "Random String Generator",
    description: "Generate random strings with custom length and characters",
    category: "text-processing",
    metaTitle: "Random String Generator Online - Free Tool | iamnoobs",
    metaDescription: "Generate random strings with custom length and character sets. Free online random string generator.",
    keywords: ["random string generator", "generate random string", "random text", "random characters"],
  },
  {
    slug: "text-shuffle",
    icon: "🔀",
    name: "Text Shuffle",
    description: "Shuffle characters, words, or lines randomly",
    category: "text-processing",
    metaTitle: "Text Shuffle Online - Randomize Text Free | iamnoobs",
    metaDescription: "Shuffle and randomize characters, words, or lines of text. Free online text shuffler.",
    keywords: ["text shuffle", "shuffle text", "randomize text", "scramble text"],
  },
  {
    slug: "remove-extra-spaces",
    icon: "✨",
    name: "Remove Extra Spaces",
    description: "Clean up extra whitespace from text",
    category: "text-processing",
    metaTitle: "Remove Extra Spaces Online - Clean Text Free | iamnoobs",
    metaDescription: "Remove extra spaces, tabs, and whitespace from text. Free online whitespace cleaner.",
    keywords: ["remove extra spaces", "trim whitespace", "clean text", "remove spaces"],
  },
  {
    slug: "character-counter",
    icon: "🔢",
    name: "Character Counter",
    description: "Count characters with and without spaces",
    category: "text-processing",
    metaTitle: "Character Counter Online - Free Tool | iamnoobs",
    metaDescription: "Count characters with and without spaces, plus word and line counts. Free online character counter.",
    keywords: ["character counter", "char count", "letter counter", "text length"],
  },
  {
    slug: "text-to-binary",
    icon: "1️⃣",
    name: "Text to Binary",
    description: "Convert text to binary representation",
    category: "text-processing",
    metaTitle: "Text to Binary Converter Online - Free Tool | iamnoobs",
    metaDescription: "Convert text to binary code (0s and 1s) instantly. Free online text to binary converter.",
    keywords: ["text to binary", "binary converter", "text binary", "ascii to binary"],
  },
  {
    slug: "binary-to-text",
    icon: "🔤",
    name: "Binary to Text",
    description: "Convert binary code back to readable text",
    category: "text-processing",
    metaTitle: "Binary to Text Converter Online - Free Tool | iamnoobs",
    metaDescription: "Convert binary code back to readable text. Free online binary to text converter.",
    keywords: ["binary to text", "decode binary", "binary decoder", "binary to ascii"],
  },
  {
    slug: "morse-code",
    icon: "📻",
    name: "Morse Code Translator",
    description: "Convert text to Morse code and back",
    category: "text-processing",
    metaTitle: "Morse Code Translator Online - Free Tool | iamnoobs",
    metaDescription: "Convert text to Morse code and Morse code to text. Free online Morse code translator.",
    keywords: ["morse code", "morse translator", "text to morse", "morse to text"],
  },

  // SECURITY TOOLS (added to generators-security)
  {
    slug: "rot13",
    icon: "🔐",
    name: "ROT13 Encoder/Decoder",
    description: "Apply ROT13 cipher to encode or decode text",
    category: "generators-security",
    metaTitle: "ROT13 Encoder/Decoder Online - Free Tool | iamnoobs",
    metaDescription: "Apply ROT13 cipher to encode or decode text. Free online ROT13 tool.",
    keywords: ["rot13", "rot13 encoder", "rot13 decoder", "caesar cipher"],
  },
  {
    slug: "password-strength-checker",
    icon: "💪",
    name: "Password Strength Checker",
    description: "Check how strong your password is",
    category: "generators-security",
    metaTitle: "Password Strength Checker Online - Free Tool | iamnoobs",
    metaDescription: "Check the strength of your password with detailed analysis. Free online password strength checker.",
    keywords: ["password strength", "password checker", "password security", "strong password check"],
  },
  {
    slug: "credit-card-validator",
    icon: "💳",
    name: "Credit Card Validator",
    description: "Validate credit card numbers using the Luhn algorithm",
    category: "generators-security",
    metaTitle: "Credit Card Validator Online - Luhn Check Free | iamnoobs",
    metaDescription: "Validate credit card numbers using the Luhn algorithm. Free online credit card number checker.",
    keywords: ["credit card validator", "luhn algorithm", "card number check", "validate card"],
  },
  {
    slug: "secure-token-generator",
    icon: "🔏",
    name: "Secure Token Generator",
    description: "Generate cryptographically secure random tokens",
    category: "generators-security",
    metaTitle: "Secure Token Generator Online - Free Tool | iamnoobs",
    metaDescription: "Generate cryptographically secure random tokens for APIs and authentication. Free token generator.",
    keywords: ["token generator", "secure token", "api token", "random token"],
  },
  {
    slug: "checksum-generator",
    icon: "🧮",
    name: "Checksum Generator",
    description: "Generate checksums for text and files",
    category: "generators-security",
    metaTitle: "Checksum Generator Online - Free Tool | iamnoobs",
    metaDescription: "Generate MD5, SHA-1, SHA-256 checksums for text and files. Free online checksum generator.",
    keywords: ["checksum generator", "file checksum", "md5 checksum", "sha256 checksum"],
  },
  {
    slug: "ssl-checker",
    icon: "🔒",
    name: "SSL Checker",
    description: "Check SSL certificate status for any domain",
    category: "generators-security",
    metaTitle: "SSL Checker Online - Verify SSL Certificate Free | iamnoobs",
    metaDescription: "Check SSL certificate status and details for any website. Free online SSL checker.",
    keywords: ["ssl checker", "ssl certificate check", "https checker", "ssl status"],
  },
  {
    slug: "http-status-checker",
    icon: "🚦",
    name: "HTTP Status Checker",
    description: "Check HTTP status codes for any URL",
    category: "generators-security",
    metaTitle: "HTTP Status Checker Online - Free Tool | iamnoobs",
    metaDescription: "Check HTTP response status codes for any URL. Free online HTTP status checker.",
    keywords: ["http status checker", "status code checker", "http response", "website status"],
  },
  {
    slug: "file-hash-checker",
    icon: "📁",
    name: "File Hash Checker",
    description: "Generate and verify file hashes",
    category: "generators-security",
    metaTitle: "File Hash Checker Online - Verify File Integrity Free | iamnoobs",
    metaDescription: "Generate and verify file hashes for integrity checking. Free online file hash checker.",
    keywords: ["file hash checker", "file integrity", "file hash verify", "hash file"],
  },

  // NEW IMAGE TOOLS
  {
    slug: "image-color-picker",
    icon: "🎨",
    name: "Image Color Picker",
    description: "Pick colors from any image",
    category: "image",
    metaTitle: "Image Color Picker Online - Pick Colors Free | iamnoobs",
    metaDescription: "Pick colors from any image and get HEX, RGB, and HSL values. Free online color picker.",
    keywords: ["image color picker", "color picker", "pick color from image", "eyedropper"],
  },
  {
    slug: "hex-rgb-converter",
    icon: "🌈",
    name: "HEX to RGB Converter",
    description: "Convert between HEX and RGB color formats",
    category: "image",
    metaTitle: "HEX to RGB Converter Online - Free Tool | iamnoobs",
    metaDescription: "Convert between HEX and RGB color formats with live preview. Free online color converter.",
    keywords: ["hex to rgb", "rgb to hex", "color converter", "hex rgb"],
  },
  {
    slug: "gradient-generator",
    icon: "🌅",
    name: "CSS Gradient Generator",
    description: "Create beautiful CSS gradients visually",
    category: "image",
    metaTitle: "CSS Gradient Generator Online - Free Tool | iamnoobs",
    metaDescription: "Create beautiful CSS linear and radial gradients visually. Free online gradient generator.",
    keywords: ["gradient generator", "css gradient", "linear gradient", "radial gradient"],
  },
  {
    slug: "favicon-generator",
    icon: "⭐",
    name: "Favicon Generator",
    description: "Generate favicons from text or emoji",
    category: "image",
    metaTitle: "Favicon Generator Online - Create Favicons Free | iamnoobs",
    metaDescription: "Generate favicons from text or emoji for your website. Free online favicon generator.",
    keywords: ["favicon generator", "create favicon", "favicon maker", "website icon"],
  },
  {
    slug: "image-metadata-viewer",
    icon: "ℹ️",
    name: "Image Metadata Viewer",
    description: "View EXIF and metadata of images",
    category: "image",
    metaTitle: "Image Metadata Viewer Online - View EXIF Free | iamnoobs",
    metaDescription: "View EXIF data and metadata of images in your browser. Free online image metadata viewer.",
    keywords: ["image metadata", "exif viewer", "image info", "photo metadata"],
  },
  {
    slug: "gif-maker",
    icon: "🎬",
    name: "GIF Maker",
    description: "Create simple animated GIFs from images",
    category: "image",
    metaTitle: "GIF Maker Online - Create GIFs Free | iamnoobs",
    metaDescription: "Create simple animated GIFs from multiple images. Free online GIF maker.",
    keywords: ["gif maker", "create gif", "animated gif", "image to gif"],
  },
  {
    slug: "image-watermark",
    icon: "💧",
    name: "Image Watermark",
    description: "Add text watermarks to images",
    category: "image",
    metaTitle: "Image Watermark Tool Online - Add Watermark Free | iamnoobs",
    metaDescription: "Add text watermarks to your images in the browser. Free online watermark tool.",
    keywords: ["image watermark", "add watermark", "watermark tool", "photo watermark"],
  },
  {
    slug: "blur-image",
    icon: "🌫️",
    name: "Blur Image",
    description: "Apply blur effect to images",
    category: "image",
    metaTitle: "Blur Image Online - Apply Blur Effect Free | iamnoobs",
    metaDescription: "Apply blur effect to your images directly in the browser. Free online image blur tool.",
    keywords: ["blur image", "image blur", "blur effect", "gaussian blur"],
  },
  {
    slug: "crop-image",
    icon: "✂️",
    name: "Crop Image",
    description: "Crop images to custom dimensions",
    category: "image",
    metaTitle: "Crop Image Online - Free Image Cropper | iamnoobs",
    metaDescription: "Crop images to custom dimensions in your browser. Free online image cropping tool.",
    keywords: ["crop image", "image cropper", "crop photo", "trim image"],
  },

  // NEW PDF & FILE TOOLS (added to document)
  {
    slug: "pdf-page-number",
    icon: "#️⃣",
    name: "PDF Page Number",
    description: "Add page numbers to PDF documents",
    category: "document",
    metaTitle: "PDF Page Number Tool Online - Add Page Numbers Free | iamnoobs",
    metaDescription: "Add page numbers to your PDF documents in the browser. Free online PDF page numbering tool.",
    keywords: ["pdf page number", "add page numbers pdf", "number pdf pages", "pdf pagination"],
  },
  {
    slug: "pdf-rotate",
    icon: "🔄",
    name: "PDF Rotate",
    description: "Rotate PDF pages by 90, 180, or 270 degrees",
    category: "document",
    metaTitle: "PDF Rotate Online - Rotate PDF Pages Free | iamnoobs",
    metaDescription: "Rotate PDF pages by 90, 180, or 270 degrees in the browser. Free online PDF rotation tool.",
    keywords: ["pdf rotate", "rotate pdf pages", "pdf rotation", "flip pdf"],
  },
  {
    slug: "pdf-unlock",
    icon: "🔓",
    name: "PDF Unlock",
    description: "Information about PDF password removal",
    category: "document",
    metaTitle: "PDF Unlock Tool Online - Free Information | iamnoobs",
    metaDescription: "Learn about PDF password removal and unlocking. Information and guidance on PDF security.",
    keywords: ["pdf unlock", "remove pdf password", "pdf password remover", "unlock pdf"],
  },
  {
    slug: "pdf-protect",
    icon: "🛡️",
    name: "PDF Protect",
    description: "Add metadata and basic protection info to PDFs",
    category: "document",
    metaTitle: "PDF Protect Online - Protect PDF Free | iamnoobs",
    metaDescription: "Add metadata and basic protection information to your PDF files. Free online PDF protection tool.",
    keywords: ["pdf protect", "protect pdf", "pdf security", "pdf password"],
  },
  {
    slug: "text-to-pdf",
    icon: "📄",
    name: "Text to PDF",
    description: "Convert plain text to PDF documents",
    category: "document",
    metaTitle: "Text to PDF Converter Online - Free Tool | iamnoobs",
    metaDescription: "Convert plain text to professional PDF documents. Free online text to PDF converter.",
    keywords: ["text to pdf", "convert text to pdf", "txt to pdf", "text pdf converter"],
  },
  {
    slug: "markdown-to-pdf",
    icon: "📑",
    name: "Markdown to PDF",
    description: "Convert Markdown to PDF documents",
    category: "document",
    metaTitle: "Markdown to PDF Converter Online - Free Tool | iamnoobs",
    metaDescription: "Convert Markdown formatted text to professional PDF documents. Free online Markdown to PDF converter.",
    keywords: ["markdown to pdf", "md to pdf", "convert markdown to pdf", "markdown pdf"],
  },
  {
    slug: "mime-type-checker",
    icon: "📋",
    name: "MIME Type Checker",
    description: "Identify MIME types of files by extension",
    category: "document",
    metaTitle: "MIME Type Checker Online - Free Tool | iamnoobs",
    metaDescription: "Identify MIME types for any file extension. Free online MIME type lookup tool.",
    keywords: ["mime type checker", "mime type", "file type", "content type"],
  },
  {
    slug: "filename-generator",
    icon: "📂",
    name: "Filename Generator",
    description: "Generate clean, safe filenames from text",
    category: "document",
    metaTitle: "Filename Generator Online - Free Tool | iamnoobs",
    metaDescription: "Generate clean, safe, and unique filenames. Free online filename generator.",
    keywords: ["filename generator", "file name generator", "safe filename", "clean filename"],
  },

  // BUSINESS & FINANCE (India-focused)
  {
    slug: "gst-calculator",
    icon: "🧾",
    name: "GST Calculator",
    description: "Calculate GST amounts for Indian tax rates",
    category: "business-finance",
    metaTitle: "GST Calculator Online - India GST Rates Free | iamnoobs",
    metaDescription: "Calculate GST amounts with Indian tax rates (5%, 12%, 18%, 28%). Free online GST calculator for India.",
    keywords: ["gst calculator", "gst calculator india", "gst amount", "igst sgst cgst"],
  },
  {
    slug: "income-tax-calculator",
    icon: "💰",
    name: "Income Tax Calculator (India)",
    description: "Calculate Indian income tax with old and new regime",
    category: "business-finance",
    metaTitle: "Income Tax Calculator India - Old & New Regime Free | iamnoobs",
    metaDescription: "Calculate Indian income tax under old and new tax regime with latest slabs. Free online income tax calculator.",
    keywords: ["income tax calculator", "income tax india", "tax calculator", "new regime old regime"],
  },
  {
    slug: "sip-calculator",
    icon: "📈",
    name: "SIP Calculator",
    description: "Calculate SIP returns and wealth creation",
    category: "business-finance",
    metaTitle: "SIP Calculator Online - Mutual Fund SIP Returns Free | iamnoobs",
    metaDescription: "Calculate SIP returns, maturity amount, and wealth creation. Free online SIP calculator for mutual funds.",
    keywords: ["sip calculator", "sip returns", "mutual fund sip", "sip investment"],
  },
  {
    slug: "loan-eligibility",
    icon: "🏠",
    name: "Loan Eligibility Calculator",
    description: "Check loan eligibility based on income",
    category: "business-finance",
    metaTitle: "Loan Eligibility Calculator Online - Free Tool | iamnoobs",
    metaDescription: "Check your loan eligibility based on income and existing EMIs. Free online loan eligibility calculator.",
    keywords: ["loan eligibility", "loan calculator", "home loan eligibility", "loan amount"],
  },
  {
    slug: "profit-margin",
    icon: "💹",
    name: "Profit Margin Calculator",
    description: "Calculate profit margin percentages",
    category: "business-finance",
    metaTitle: "Profit Margin Calculator Online - Free Tool | iamnoobs",
    metaDescription: "Calculate gross and net profit margins for your business. Free online profit margin calculator.",
    keywords: ["profit margin calculator", "gross margin", "net margin", "profit percentage"],
  },
  {
    slug: "break-even",
    icon: "⚖️",
    name: "Break-Even Calculator",
    description: "Calculate break-even point for businesses",
    category: "business-finance",
    metaTitle: "Break-Even Calculator Online - Free Tool | iamnoobs",
    metaDescription: "Calculate the break-even point for your business. Free online break-even analysis tool.",
    keywords: ["break even calculator", "break even point", "break even analysis", "business calculator"],
  },
  {
    slug: "invoice-generator",
    icon: "🧾",
    name: "Invoice Generator",
    description: "Create professional invoices instantly",
    category: "business-finance",
    metaTitle: "Invoice Generator Online - Create Invoices Free | iamnoobs",
    metaDescription: "Create professional invoices with GST support instantly. Free online invoice generator.",
    keywords: ["invoice generator", "create invoice", "invoice maker", "gst invoice"],
  },
  {
    slug: "salary-calculator",
    icon: "💵",
    name: "Salary Calculator (India)",
    description: "Calculate in-hand salary from CTC",
    category: "business-finance",
    metaTitle: "Salary Calculator India - CTC to In-Hand Free | iamnoobs",
    metaDescription: "Calculate in-hand salary from CTC with PF, PT, and tax deductions. Free Indian salary calculator.",
    keywords: ["salary calculator", "ctc to in-hand", "salary breakup", "net salary india"],
  },
  {
    slug: "freelance-rate",
    icon: "🧑‍💻",
    name: "Freelance Rate Calculator",
    description: "Calculate your ideal freelance hourly rate",
    category: "business-finance",
    metaTitle: "Freelance Rate Calculator Online - Free Tool | iamnoobs",
    metaDescription: "Calculate your ideal freelance hourly or project rate based on expenses and goals. Free rate calculator.",
    keywords: ["freelance rate calculator", "hourly rate", "freelance pricing", "rate calculator"],
  },
  {
    slug: "savings-goal",
    icon: "🎯",
    name: "Savings Goal Calculator",
    description: "Plan monthly savings for your financial goals",
    category: "business-finance",
    metaTitle: "Savings Goal Calculator Online - Free Tool | iamnoobs",
    metaDescription: "Plan your monthly savings to reach financial goals. Free online savings goal calculator.",
    keywords: ["savings goal", "savings calculator", "financial goal", "monthly savings"],
  },

  // PRODUCTIVITY
  {
    slug: "todo-list",
    icon: "✅",
    name: "Todo List",
    description: "Manage your tasks with a local todo list",
    category: "productivity",
    metaTitle: "Todo List Online - Free Task Manager | iamnoobs",
    metaDescription: "Manage your tasks with a simple, private todo list saved in your browser. Free online task manager.",
    keywords: ["todo list", "task manager", "todo app", "task list"],
  },
  {
    slug: "notes-app",
    icon: "📝",
    name: "Notes App",
    description: "Take and save notes offline in your browser",
    category: "productivity",
    metaTitle: "Notes App Online - Free Offline Notes | iamnoobs",
    metaDescription: "Take and save notes offline in your browser. Free online notepad with local storage.",
    keywords: ["notes app", "online notepad", "take notes", "browser notes"],
  },
  {
    slug: "pomodoro-timer",
    icon: "🍅",
    name: "Pomodoro Timer",
    description: "Boost productivity with the Pomodoro technique",
    category: "productivity",
    metaTitle: "Pomodoro Timer Online - Focus Timer Free | iamnoobs",
    metaDescription: "Boost your productivity with the Pomodoro technique. Free online Pomodoro timer with breaks.",
    keywords: ["pomodoro timer", "focus timer", "productivity timer", "pomodoro technique"],
  },
  {
    slug: "random-decision-wheel",
    icon: "🎡",
    name: "Random Decision Wheel",
    description: "Spin a wheel to make random decisions",
    category: "productivity",
    metaTitle: "Random Decision Wheel Online - Free Spinner | iamnoobs",
    metaDescription: "Spin a wheel to make random decisions. Add custom options and let the wheel decide. Free online spinner.",
    keywords: ["decision wheel", "random wheel", "spin wheel", "random picker"],
  },
  {
    slug: "habit-tracker",
    icon: "📅",
    name: "Habit Tracker",
    description: "Track daily habits with streaks",
    category: "productivity",
    metaTitle: "Habit Tracker Online - Track Habits Free | iamnoobs",
    metaDescription: "Track your daily habits with streaks and progress. Free online habit tracker.",
    keywords: ["habit tracker", "track habits", "daily habits", "streak tracker"],
  },
  {
    slug: "daily-planner",
    icon: "🗓️",
    name: "Daily Planner",
    description: "Plan your day with time blocks",
    category: "productivity",
    metaTitle: "Daily Planner Online - Plan Your Day Free | iamnoobs",
    metaDescription: "Plan your day with time blocks and tasks. Free online daily planner.",
    keywords: ["daily planner", "day planner", "schedule planner", "time blocking"],
  },
  {
    slug: "meeting-time-finder",
    icon: "🤝",
    name: "Meeting Time Finder",
    description: "Find common meeting times across timezones",
    category: "productivity",
    metaTitle: "Meeting Time Finder Online - Free Tool | iamnoobs",
    metaDescription: "Find common meeting times across different timezones. Free timezone meeting planner.",
    keywords: ["meeting time finder", "timezone meeting", "schedule meeting", "time overlap"],
  },
  {
    slug: "countdown-timer",
    icon: "⏳",
    name: "Countdown Timer",
    description: "Set a countdown to any date or time",
    category: "productivity",
    metaTitle: "Countdown Timer Online - Free Timer | iamnoobs",
    metaDescription: "Set a countdown timer to any date, event, or duration. Free online countdown timer.",
    keywords: ["countdown timer", "timer", "countdown clock", "event countdown"],
  },
  {
    slug: "stopwatch",
    icon: "⏱️",
    name: "Stopwatch",
    description: "Online stopwatch with lap timer",
    category: "productivity",
    metaTitle: "Stopwatch Online - Free Stopwatch with Laps | iamnoobs",
    metaDescription: "Online stopwatch with lap timer functionality. Free and precise stopwatch tool.",
    keywords: ["stopwatch", "online stopwatch", "lap timer", "timer"],
  },
  {
    slug: "random-number",
    icon: "🎲",
    name: "Random Number Generator",
    description: "Generate random numbers within a range",
    category: "productivity",
    metaTitle: "Random Number Generator Online - Free Tool | iamnoobs",
    metaDescription: "Generate random numbers within a custom range. Free online random number generator.",
    keywords: ["random number generator", "random number", "number generator", "rng"],
  },

  // SEO TOOLS (added to seo-content)
  {
    slug: "sitemap-generator",
    icon: "🗺️",
    name: "Sitemap Generator",
    description: "Generate XML sitemaps for your website",
    category: "seo-content",
    metaTitle: "Sitemap Generator Online - Create XML Sitemap Free | iamnoobs",
    metaDescription: "Generate XML sitemaps for your website with custom URLs. Free online sitemap generator.",
    keywords: ["sitemap generator", "xml sitemap", "create sitemap", "seo sitemap"],
  },
  {
    slug: "robots-txt-generator",
    icon: "🤖",
    name: "Robots.txt Generator",
    description: "Generate robots.txt files for your website",
    category: "seo-content",
    metaTitle: "Robots.txt Generator Online - Free Tool | iamnoobs",
    metaDescription: "Generate robots.txt files for search engine crawling control. Free online robots.txt generator.",
    keywords: ["robots.txt generator", "robots txt", "create robots.txt", "crawl control"],
  },
  {
    slug: "canonical-tag-generator",
    icon: "🔖",
    name: "Canonical Tag Generator",
    description: "Generate canonical link tags for SEO",
    category: "seo-content",
    metaTitle: "Canonical Tag Generator Online - Free Tool | iamnoobs",
    metaDescription: "Generate canonical link tags to prevent duplicate content issues. Free canonical tag generator.",
    keywords: ["canonical tag", "canonical url", "rel canonical", "duplicate content"],
  },
  {
    slug: "htaccess-redirect-generator",
    icon: "↪️",
    name: ".htaccess Redirect Generator",
    description: "Generate .htaccess redirect rules",
    category: "seo-content",
    metaTitle: ".htaccess Redirect Generator Online - Free Tool | iamnoobs",
    metaDescription: "Generate .htaccess redirect rules (301, 302) for Apache servers. Free online redirect generator.",
    keywords: ["htaccess redirect", "301 redirect", "htaccess generator", "url redirect"],
  },
  {
    slug: "keyword-suggestion",
    icon: "💡",
    name: "Keyword Suggestion Tool",
    description: "Get keyword ideas and suggestions",
    category: "seo-content",
    metaTitle: "Keyword Suggestion Tool Online - Free SEO Tool | iamnoobs",
    metaDescription: "Get keyword ideas and variations for your content strategy. Free keyword suggestion tool.",
    keywords: ["keyword suggestion", "keyword ideas", "keyword research", "seo keywords"],
  },
  {
    slug: "broken-link-checker",
    icon: "🔗",
    name: "Broken Link Checker",
    description: "Check URLs for broken links",
    category: "seo-content",
    metaTitle: "Broken Link Checker Online - Free Tool | iamnoobs",
    metaDescription: "Check URLs for broken links and 404 errors. Free online broken link checker.",
    keywords: ["broken link checker", "dead link checker", "link validator", "404 checker"],
  },
  {
    slug: "website-screenshot",
    icon: "📸",
    name: "Website Screenshot",
    description: "Capture screenshots of websites",
    category: "seo-content",
    metaTitle: "Website Screenshot Tool Online - Free | iamnoobs",
    metaDescription: "Capture screenshots of any website for free. Online website screenshot tool.",
    keywords: ["website screenshot", "capture website", "screenshot tool", "webpage capture"],
  },
  {
    slug: "whois-lookup",
    icon: "🔎",
    name: "WHOIS Lookup",
    description: "Look up domain WHOIS information",
    category: "seo-content",
    metaTitle: "WHOIS Lookup Online - Domain Info Free | iamnoobs",
    metaDescription: "Look up WHOIS information for any domain. Free online WHOIS lookup tool.",
    keywords: ["whois lookup", "domain whois", "domain info", "domain registration"],
  },

  // DEV HELPERS
  {
    slug: "cron-generator",
    icon: "⏰",
    name: "Cron Expression Generator",
    description: "Generate and explain cron expressions",
    category: "dev-helpers",
    metaTitle: "Cron Expression Generator Online - Free Tool | iamnoobs",
    metaDescription: "Generate and understand cron expressions with a visual builder. Free cron expression generator.",
    keywords: ["cron generator", "cron expression", "crontab", "cron schedule"],
  },
  {
    slug: "timestamp-converter",
    icon: "🕐",
    name: "Timestamp Converter",
    description: "Convert between Unix timestamps and dates",
    category: "dev-helpers",
    metaTitle: "Timestamp Converter Online - Unix Epoch Free | iamnoobs",
    metaDescription: "Convert between Unix timestamps and human-readable dates. Free online timestamp converter.",
    keywords: ["timestamp converter", "unix timestamp", "epoch converter", "date to timestamp"],
  },
  {
    slug: "color-converter",
    icon: "🎨",
    name: "Color Converter",
    description: "Convert between HEX, RGB, HSL color formats",
    category: "dev-helpers",
    metaTitle: "Color Converter Online - HEX RGB HSL Free | iamnoobs",
    metaDescription: "Convert between HEX, RGB, and HSL color formats with live preview. Free online color converter.",
    keywords: ["color converter", "hex to rgb", "rgb to hsl", "color format"],
  },
  {
    slug: "html-entities",
    icon: "🏷️",
    name: "HTML Entities Encoder",
    description: "Encode and decode HTML entities",
    category: "dev-helpers",
    metaTitle: "HTML Entities Encoder/Decoder Online - Free Tool | iamnoobs",
    metaDescription: "Encode and decode HTML entities. Free online HTML entity converter.",
    keywords: ["html entities", "html encode", "html decode", "special characters"],
  },
  {
    slug: "js-obfuscator",
    icon: "🫥",
    name: "JS Obfuscator",
    description: "Basic JavaScript code obfuscation",
    category: "dev-helpers",
    metaTitle: "JavaScript Obfuscator Online - Free Tool | iamnoobs",
    metaDescription: "Basic JavaScript code obfuscation. Free online JS obfuscator tool.",
    keywords: ["js obfuscator", "javascript obfuscator", "obfuscate code", "code protection"],
  },
  {
    slug: "js-deobfuscator",
    icon: "👁️",
    name: "JS Deobfuscator",
    description: "Basic JavaScript code deobfuscation and beautification",
    category: "dev-helpers",
    metaTitle: "JavaScript Deobfuscator Online - Free Tool | iamnoobs",
    metaDescription: "Deobfuscate and beautify JavaScript code. Free online JS deobfuscator.",
    keywords: ["js deobfuscator", "javascript deobfuscator", "deobfuscate code", "code beautifier"],
  },
  {
    slug: "markdown-editor",
    icon: "✏️",
    name: "Markdown Editor",
    description: "Write and preview Markdown in real-time",
    category: "dev-helpers",
    metaTitle: "Markdown Editor Online - Live Preview Free | iamnoobs",
    metaDescription: "Write and preview Markdown with real-time rendering. Free online Markdown editor.",
    keywords: ["markdown editor", "markdown preview", "md editor", "markdown live preview"],
  },
  {
    slug: "api-tester",
    icon: "🚀",
    name: "API Tester",
    description: "Test API endpoints with GET, POST, PUT, DELETE",
    category: "dev-helpers",
    metaTitle: "API Tester Online - Test REST APIs Free | iamnoobs",
    metaDescription: "Test REST API endpoints with custom methods, headers, and body. Free online API testing tool.",
    keywords: ["api tester", "rest api tester", "api client", "test api"],
  },
  {
    slug: "graphql-tester",
    icon: "🔮",
    name: "GraphQL Tester",
    description: "Test GraphQL queries and mutations",
    category: "dev-helpers",
    metaTitle: "GraphQL Tester Online - Free Tool | iamnoobs",
    metaDescription: "Test GraphQL queries and mutations against any endpoint. Free online GraphQL testing tool.",
    keywords: ["graphql tester", "graphql client", "test graphql", "graphql query"],
  },

  // CSS & DESIGN TOOLS
  {
    slug: "box-shadow-generator",
    icon: "🖱️",
    name: "Box Shadow Generator",
    description: "Create CSS box shadows with live preview",
    category: "css-design",
    metaTitle: "CSS Box Shadow Generator Online - Free Tool | iamnoobs",
    metaDescription: "Create beautiful CSS box shadows with a visual editor and live preview. Free online box shadow generator.",
    keywords: ["box shadow generator", "css box shadow", "shadow generator", "css shadow"],
  },
  {
    slug: "flexbox-generator",
    icon: "📦",
    name: "Flexbox Generator",
    description: "Generate CSS flexbox layouts visually",
    category: "css-design",
    metaTitle: "CSS Flexbox Generator Online - Free Tool | iamnoobs",
    metaDescription: "Create CSS flexbox layouts with a visual editor. Free online flexbox code generator.",
    keywords: ["flexbox generator", "css flexbox", "flexbox layout", "flex container"],
  },
  {
    slug: "grid-generator",
    icon: "🔲",
    name: "CSS Grid Generator",
    description: "Build CSS grid layouts with visual controls",
    category: "css-design",
    metaTitle: "CSS Grid Generator Online - Free Tool | iamnoobs",
    metaDescription: "Build CSS grid layouts visually with rows, columns, and gap controls. Free online CSS grid generator.",
    keywords: ["css grid generator", "grid layout", "css grid", "grid template"],
  },
  {
    slug: "border-radius-generator",
    icon: "⭕",
    name: "Border Radius Generator",
    description: "Generate CSS border-radius with visual preview",
    category: "css-design",
    metaTitle: "CSS Border Radius Generator Online - Free Tool | iamnoobs",
    metaDescription: "Generate CSS border-radius values with a visual editor and preview. Free online border radius tool.",
    keywords: ["border radius generator", "css border radius", "rounded corners", "border radius preview"],
  },
  {
    slug: "css-animation-generator",
    icon: "🎭",
    name: "CSS Animation Generator",
    description: "Create CSS keyframe animations visually",
    category: "css-design",
    metaTitle: "CSS Animation Generator Online - Free Tool | iamnoobs",
    metaDescription: "Create CSS keyframe animations with visual controls. Free online CSS animation builder.",
    keywords: ["css animation generator", "keyframe animation", "css animation", "animate css"],
  },
  {
    slug: "color-palette-generator",
    icon: "🎨",
    name: "Color Palette Generator",
    description: "Generate harmonious color palettes from a base color",
    category: "css-design",
    metaTitle: "Color Palette Generator Online - Free Tool | iamnoobs",
    metaDescription: "Generate beautiful color palettes with complementary, analogous, and triadic schemes. Free online palette tool.",
    keywords: ["color palette generator", "color scheme", "color palette", "harmonious colors"],
  },

  // HIGH-VALUE TOOLS (daily-use / generators-security)
  {
    slug: "qr-code-generator",
    icon: "📱",
    name: "QR Code Generator",
    description: "Generate QR codes for URLs, text, and more",
    category: "generators-security",
    metaTitle: "QR Code Generator Online - Free Tool | iamnoobs",
    metaDescription: "Generate QR codes for URLs, text, WiFi, and more. Download as PNG. Free online QR code generator.",
    keywords: ["qr code generator", "generate qr code", "qr maker", "qr code creator"],
  },
  {
    slug: "barcode-generator",
    icon: "📊",
    name: "Barcode Generator",
    description: "Generate barcodes in various formats",
    category: "generators-security",
    metaTitle: "Barcode Generator Online - Free Tool | iamnoobs",
    metaDescription: "Generate barcodes in Code128, EAN-13, and other formats. Free online barcode generator with download.",
    keywords: ["barcode generator", "generate barcode", "code128", "ean13 barcode"],
  },
  {
    slug: "bmi-calculator",
    icon: "⚖️",
    name: "BMI Calculator",
    description: "Calculate Body Mass Index with health classification",
    category: "daily-use",
    metaTitle: "BMI Calculator Online - Free Tool | iamnoobs",
    metaDescription: "Calculate your Body Mass Index (BMI) with health classification. Free online BMI calculator.",
    keywords: ["bmi calculator", "body mass index", "bmi checker", "health calculator"],
  },
  {
    slug: "compound-interest-calculator",
    icon: "📈",
    name: "Compound Interest Calculator",
    description: "Calculate compound interest with detailed breakdown",
    category: "daily-use",
    metaTitle: "Compound Interest Calculator Online - Free Tool | iamnoobs",
    metaDescription: "Calculate compound interest with yearly breakdown and growth visualization. Free online calculator.",
    keywords: ["compound interest calculator", "compound interest", "interest calculator", "investment calculator"],
  },
  {
    slug: "number-base-converter",
    icon: "🔢",
    name: "Number Base Converter",
    description: "Convert between binary, octal, decimal, and hexadecimal",
    category: "daily-use",
    metaTitle: "Number Base Converter Online - Free Tool | iamnoobs",
    metaDescription: "Convert numbers between binary, octal, decimal, and hexadecimal systems. Free online number base converter.",
    keywords: ["number base converter", "binary converter", "hex converter", "octal converter"],
  },
  {
    slug: "text-to-speech",
    icon: "🔊",
    name: "Text to Speech",
    description: "Convert text to speech using Web Speech API",
    category: "daily-use",
    metaTitle: "Text to Speech Online - Free Tool | iamnoobs",
    metaDescription: "Convert text to speech with adjustable voice, speed, and pitch. Free online text to speech tool.",
    keywords: ["text to speech", "tts", "speech synthesis", "read text aloud"],
  },

  // DEV TOOLS (dev-helpers)
  {
    slug: "chmod-calculator",
    icon: "🔒",
    name: "chmod Calculator",
    description: "Calculate Unix file permissions in numeric and symbolic",
    category: "dev-helpers",
    metaTitle: "chmod Calculator Online - Free Tool | iamnoobs",
    metaDescription: "Calculate Unix/Linux file permissions with numeric and symbolic notation. Free online chmod calculator.",
    keywords: ["chmod calculator", "file permissions", "unix permissions", "linux chmod"],
  },
  {
    slug: "git-command-generator",
    icon: "📚",
    name: "Git Command Generator",
    description: "Generate git commands for common operations",
    category: "dev-helpers",
    metaTitle: "Git Command Generator Online - Free Tool | iamnoobs",
    metaDescription: "Generate git commands for branching, merging, rebasing, and more. Free online git command reference.",
    keywords: ["git command generator", "git commands", "git reference", "git cheat sheet"],
  },
  {
    slug: "json-schema-validator",
    icon: "📋",
    name: "JSON Schema Validator",
    description: "Validate JSON data against a JSON Schema",
    category: "dev-helpers",
    metaTitle: "JSON Schema Validator Online - Free Tool | iamnoobs",
    metaDescription: "Validate JSON data against a JSON Schema definition. Free online JSON schema validation tool.",
    keywords: ["json schema validator", "validate json schema", "json schema", "schema validation"],
  },
  {
    slug: "gitignore-generator",
    icon: "🙈",
    name: ".gitignore Generator",
    description: "Generate .gitignore files for your projects",
    category: "dev-helpers",
    metaTitle: ".gitignore Generator Online - Free Tool | iamnoobs",
    metaDescription: "Generate .gitignore files for Node.js, Python, Java, and more. Free online gitignore generator.",
    keywords: ["gitignore generator", "git ignore", "gitignore template", "gitignore file"],
  },
  {
    slug: "package-json-generator",
    icon: "📦",
    name: "package.json Generator",
    description: "Generate package.json files for Node.js projects",
    category: "dev-helpers",
    metaTitle: "package.json Generator Online - Free Tool | iamnoobs",
    metaDescription: "Generate package.json files for Node.js projects with custom fields. Free online package.json generator.",
    keywords: ["package.json generator", "npm init", "package json", "node.js package"],
  },
  {
    slug: "ip-subnet-calculator",
    icon: "🌐",
    name: "IP Subnet Calculator",
    description: "Calculate IP subnets, CIDR, and network ranges",
    category: "dev-helpers",
    metaTitle: "IP Subnet Calculator Online - Free Tool | iamnoobs",
    metaDescription: "Calculate IP subnets, CIDR notation, network address, and broadcast address. Free online subnet calculator.",
    keywords: ["subnet calculator", "ip subnet", "cidr calculator", "network calculator"],
  },

  // ENCODING & CRYPTO
  {
    slug: "aes-encrypt-decrypt",
    icon: "🔐",
    name: "AES Encrypt/Decrypt",
    description: "Encrypt and decrypt text using AES-GCM",
    category: "generators-security",
    metaTitle: "AES Encrypt Decrypt Online - Free Tool | iamnoobs",
    metaDescription: "Encrypt and decrypt text using AES-GCM with the Web Crypto API. Free online AES encryption tool.",
    keywords: ["aes encrypt", "aes decrypt", "aes encryption", "aes-gcm online"],
  },
  {
    slug: "caesar-cipher",
    icon: "🏛️",
    name: "Caesar Cipher",
    description: "Encrypt and decrypt text with Caesar shift cipher",
    category: "generators-security",
    metaTitle: "Caesar Cipher Online - Encrypt & Decrypt | iamnoobs",
    metaDescription: "Encrypt and decrypt text using the Caesar cipher with custom shift values. Free online Caesar cipher tool.",
    keywords: ["caesar cipher", "caesar shift", "cipher encoder", "shift cipher"],
  },

  // FUN & SOCIAL
  {
    slug: "typing-speed-test",
    icon: "⌨️",
    name: "Typing Speed Test",
    description: "Test your typing speed and accuracy",
    category: "fun-social",
    metaTitle: "Typing Speed Test Online - Free Tool | iamnoobs",
    metaDescription: "Test your typing speed and accuracy with WPM tracking. Free online typing test.",
    keywords: ["typing speed test", "typing test", "wpm test", "typing speed"],
  },
  {
    slug: "ascii-art-generator",
    icon: "🎨",
    name: "ASCII Art Generator",
    description: "Convert text to ASCII art in various fonts",
    category: "fun-social",
    metaTitle: "ASCII Art Generator Online - Free Tool | iamnoobs",
    metaDescription: "Convert text into ASCII art with various font styles. Free online ASCII art generator.",
    keywords: ["ascii art generator", "text to ascii", "ascii art", "text art"],
  },
  {
    slug: "readability-checker",
    icon: "📖",
    name: "Readability Checker",
    description: "Check text readability with Flesch-Kincaid scores",
    category: "fun-social",
    metaTitle: "Readability Checker Online - Free Tool | iamnoobs",
    metaDescription: "Check your text's readability with Flesch-Kincaid and other scoring methods. Free online readability checker.",
    keywords: ["readability checker", "flesch kincaid", "readability score", "text readability"],
  },
  {
    slug: "social-image-resizer",
    icon: "📲",
    name: "Social Media Image Resizer",
    description: "Resize images for social media platforms",
    category: "fun-social",
    metaTitle: "Social Media Image Resizer Online - Free Tool | iamnoobs",
    metaDescription: "Resize images for Instagram, Twitter/X, Facebook, LinkedIn, and YouTube. Free online social media image resizer.",
    keywords: ["social media image resizer", "instagram image size", "twitter image size", "resize for social media"],
  },
  {
    slug: "twitter-character-counter",
    icon: "🐦",
    name: "Twitter/X Character Counter",
    description: "Count characters for Twitter/X posts with limit tracking",
    category: "fun-social",
    metaTitle: "Twitter Character Counter Online - Free Tool | iamnoobs",
    metaDescription: "Count characters for Twitter/X posts and see remaining characters. Free online Twitter character counter.",
    keywords: ["twitter character counter", "x character counter", "tweet length", "tweet character limit"],
  },
  {
    slug: "youtube-thumbnail-preview",
    icon: "🎥",
    name: "YouTube Thumbnail Preview",
    description: "Preview custom YouTube thumbnails at various sizes",
    category: "fun-social",
    metaTitle: "YouTube Thumbnail Preview Online - Free Tool | iamnoobs",
    metaDescription: "Preview how your YouTube thumbnail will look at different sizes. Free online thumbnail preview tool.",
    keywords: ["youtube thumbnail preview", "thumbnail preview", "youtube thumbnail", "thumbnail checker"],
  },
];

export function getToolBySlug(slug: string): ToolConfig | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getToolsByCategory(categorySlug: string): ToolConfig[] {
  return tools.filter((t) => t.category === categorySlug);
}
